/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gspetbloxcpwsvacotzm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzcGV0YmxveGNwd3N2YWNvdHptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4MjYxMDYsImV4cCI6MjA5MjQwMjEwNn0.3i7JIMiA4Bzgbk5vnwq-1H9Z36CjUNu2SWFE4R-r8xY"